# Generated by Django 2.0.4 on 2018-04-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=30)),
                ('surname', models.CharField(help_text='Enter surname', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Enter email', max_length=50)),
                ('name', models.CharField(help_text='Enter name', max_length=30)),
                ('surname', models.CharField(help_text='Enter surname', max_length=40)),
                ('is_admin', models.BooleanField(help_text='Is this user an admin?')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='referenced_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.User'),
        ),
    ]
