# Generated by Django 2.0.4 on 2018-04-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180427_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', help_text='Enter an optional image', upload_to='img_folder/'),
        ),
    ]
