# Generated by Django 2.0.4 on 2018-04-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180429_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Enter name', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(help_text='Enter surname', max_length=50),
        ),
    ]
