# Generated by Django 2.0.4 on 2018-04-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20180429_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referenced_user',
            field=models.CharField(max_length=150),
        ),
    ]
