# Generated by Django 2.0.4 on 2018-05-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20180430_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default='img_folder/default.png', help_text='Enter an optional image', null=True, upload_to='img_folder/'),
        ),
    ]
