# Generated by Django 2.0.4 on 2018-05-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20180501_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(default='img_folder/default.png', help_text='Enter an optional image', upload_to='img_folder/'),
        ),
    ]
