# Generated by Django 2.0.4 on 2018-05-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20180501_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='referenced_user',
            new_name='last_modified_by_user',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by_user',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
