# Generated by Django 2.0.4 on 2018-05-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('photo', models.ImageField(default='img_folder/default.png', help_text='Optional', upload_to='img_folder/')),
                ('last_modified_by_user', models.CharField(max_length=150)),
                ('created_by_user', models.CharField(max_length=150)),
            ],
        ),
    ]
