# Generated by Django 2.0.4 on 2018-05-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_by_user',
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_modified_by_user',
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
